variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/**/build/libs/*.jar*"
  ARTIFACTS: "$CI_PROJECT_DIR/*.jar*"
  GRADLE_OPTS: >
    -Dorg.gradle.project.branchName="$CI_COMMIT_REF_NAME"
    -Dorg.gradle.project.curseForgeApiKey="$curseForgeApiKey"
    -Dorg.gradle.project.keyStoreAlias="$keyStoreAlias"
    -Dorg.gradle.project.keyStore="$keyStore"
    -Dorg.gradle.project.keyStorePass="$keyStorePass"

cache:
  key: "$CI_COMMIT_REF_NAME_$CI_COMMIT_SHA"
  untracked: true

before_script:
  - shopt -s globstar
  - shopt -s nullglob

stages:
- build
- test
- deploy
  
build:
  stage: build
  script:
  - ./gradlew --console=plain en2ud assemble
  - cp $ORIG_ARTIFACTS .
  when: on_success
  artifacts:
    paths:
    - $ARTIFACTS

checkTranslations:
  stage: test
  script:
  - ./gradlew --continue --console=plain checkTranslations
  - if test -n "$(find . -maxdepth 1 -name '*.lang.txt' -print -quit)"; then
  - tail -vn+1 *.lang.txt
  - exit 1
  - fi
  when: on_success
  allow_failure: true
    
deploy:
  stage: deploy
  script:
  - ./gradlew --console=plain uploadArchives curseforge
  when: on_success
  only:
  - tags