variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/BrainStoneMod-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/BrainStoneMod-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- build
- deploy
- checkTranslations
- cleanup
  
build:
  stage: build
  script:
  - ./gradlew --console=plain clean
  - ./gradlew --console=plain assemble
  - cp $ORIG_ARTIFACTS .
  when: on_success
  artifacts:
    name: "BrainStoneMod-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
    
deploy:
  stage: deploy
  script:
  - ./gradlew --console=plain uploadArchives curseforge updateDownloadServer -Psecret=$secret -PcurseForgeApiKey=$curseForgeApiKey
  when: on_success
  only:
  - tags
  
checkTranslations:
  stage: checkTranslations
  script:
  - ./gradlew --console=plain checkTranslations
  - if test -n "$(find . -maxdepth 1 -name '*.lang.txt' -print -quit)"; then
  - tail -vn+1 *.lang.txt
  - exit 1
  - fi
  when: on_success
  allow_failure: true
  except:
  - tags

cleanup:
  stage: cleanup
  script:
  - ./gradlew --console=plain clean
  - rm -vf $ARTIFACTS *.lang.txt
  - mkdir -p $CACHE_DIR $CACHE_DIR2
  when: always
