variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/BrainStoneMod-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/BrainStoneMod-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- build
- deploy
- cleanup

before_script:
  - shopt -s extglob
  
build:
  stage: build
  script:
  - ./gradlew assemble
  - cp $ORIG_ARTIFACTS .
  when: on_success
  only:
  - master
  - tags
  artifacts:
    name: "BrainStoneMod-$(grep 'mod_version=' build.properties | sed 's/^.*=//' | sed "s/\?/$(git rev-list --count $(git log --follow -1 --pretty=%H build.properties)..HEAD)/g")"
    paths:
    - $ARTIFACTS
    
deploy:
  stage: deploy
  script:
  - ./gradlew curseforge
  when: on_success
  only:
  - tags

cleanup:
  stage: cleanup
  script:
  - ./gradlew clean
  - rm -vf $ARTIFACTS
  - mkdir -p $CACHE_DIR $CACHE_DIR2
  when: always
  only:
  - master
  - tags
