variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/BrainStoneMod-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/BrainStoneMod-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- build
- deploy
- cleanup

before_script:
  - shopt -s extglob
  
build:
  stage: build
  script:
  - ./gradlew assemble
  - cp $ORIG_ARTIFACTS .
  when: on_success
  artifacts:
    name: "BrainStoneMod-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS
    
deploy:
  stage: deploy
  script:
  - ./gradlew uploadArchives curseforge updateDownloadServer -Psecret=$secret -PcurseForgeApiKey=$curseForgeApiKey
  when: on_success
  only:
  - tags

cleanup:
  stage: cleanup
  script:
  - ./gradlew clean
  - rm -vf $ARTIFACTS
  - mkdir -p $CACHE_DIR $CACHE_DIR2
  when: always
